@if($show){!! $content !!}@endif
</div>
<noscript>
    <style>
        .lazyload{display:none;}
    </style>
</noscript>
<script data-noptimize="1">window.lazySizesConfig=window.lazySizesConfig||{};window.lazySizesConfig.loadMode=1;</script>
<script async data-noptimize="1" src='{{asset('wp-content/plugins/autoptimize/classes/external/js/lazysizes.min.js')}}'></script>
<script type='text/javascript'>var wp_load_style = ["wp-block-library.css","contact-form-7.html","kava-theme-style.html","kava-theme-main-style.html","blog-layouts-module.html","cx-google-fonts-kava.html","jet-menu-public.html","cherry-handler-css.html","jet-popup-frontend.html","jet-blocks.html","jet-elements.html","jet-elements-skin.html","elementor-icons.html","elementor-animations.html","elementor-frontend.html","jet-blog.html","jet-tabs-frontend.html","jet-tricks-frontend.html","kava-extra-nucleo-outline.html","google-fonts-1.html","elementor-icons-fa-solid.html","elementor-icons-fa-brands.css"];
    var wp_load_script = ["cherry-js-core.js","contact-form-8.html","kava-theme-script.html","jet-menu-public-2.html","cherry-handler-js.js"];
    var cherry_ajax = "33065ac70a";
    var ui_init_object = {"auto_init":"false","targets":[]};</script>
<script type='text/javascript'>function CherryCSSCollector(){"use strict";var t,e=window.CherryCollectedCSS;void 0!==e&&(t=document.createElement("style"),t.setAttribute("title",e.title),t.setAttribute("type",e.type),t.textContent=e.css,document.head.appendChild(t))}CherryCSSCollector();</script>
<script type='text/javascript'>var wpcf7 = {"apiSettings":{"root":"https:\/\/ld-wp73.template-help.com\/wordpress\/prod_6014\/v1\/wp-json\/contact-form-7\/v1","namespace":"contact-form-7\/v1"}};</script>
<script type='text/javascript'>var kavaConfig = {"toTop":"1"};</script>
<script type='text/javascript'>function CxCSSCollector(){"use strict";var t,e=window.CxCollectedCSS;void 0!==e&&((t=document.createElement("style")).setAttribute("title",e.title),t.setAttribute("type",e.type),t.textContent=e.css,document.head.appendChild(t))}CxCSSCollector();</script>
<script type='text/javascript'>var jetMenuPublicSettings = {"menuSettings":{"jetMenuRollUp":"false","jetMenuMouseleaveDelay":500,"jetMenuMegaWidthType":"container","jetMenuMegaWidthSelector":"","jetMenuMegaOpenSubType":"hover","jetMenuMobileBreakpoint":768}};</script>
<script type='text/javascript'>var jet_menu_save_options_ajax = {"action":"jet_menu_save_options_ajax","nonce":"642aef3286","type":"POST","data_type":"json","is_public":"false","sys_messages":{"invalid_base_data":"Unable to process the request without nonce or server error","no_right":"No right for this action","invalid_nonce":"Stop CHEATING!!!","access_is_allowed":"","wait_processing":"Please wait, processing the previous request"}};
    var jet_menu_restore_options_ajax = {"action":"jet_menu_restore_options_ajax","nonce":"1c227e000c","type":"POST","data_type":"json","is_public":"false","sys_messages":{"invalid_base_data":"Unable to process the request without nonce or server error","no_right":"No right for this action","invalid_nonce":"Stop CHEATING!!!","access_is_allowed":"","wait_processing":"Please wait, processing the previous request"}};</script>
<script type='text/javascript'>var elementorFrontendConfig = {"environmentMode":{"edit":false,"wpPreview":false},"is_rtl":false,"breakpoints":{"xs":0,"sm":480,"md":768,"lg":1025,"xl":1440,"xxl":1600},"version":"2.8.2","urls":{"assets":"https:\/\/ld-wp73.template-help.com\/wordpress\/prod_6014\/v1\/wp-content\/plugins\/elementor\/assets\/"},"settings":{"page":[],"general":{"elementor_global_image_lightbox":"yes"},"editorPreferences":[]},"post":{"id":22,"title":"Home","excerpt":""}};</script>
<script type='text/javascript'>var jetElements = {"ajaxUrl":"https:\/\/ld-wp73.template-help.com\/wordpress\/prod_6014\/v1\/wp-admin\/admin-ajax.php","isMobile":"false","templateApiUrl":"https:\/\/ld-wp73.template-help.com\/wordpress\/prod_6014\/v1\/wp-json\/jet-elements-api\/v1\/elementor-template","devMode":"false","messages":{"invalidMail":"Please specify a valid e-mail"}};</script>
<script type='text/javascript'>var jetPopupData = {"elements_data":{"sections":[],"columns":[],"widgets":{"1aecb79":{"attached-popup":"jet-popup-500","trigger-type":"click-self","trigger-custom-selector":""}}},"version":"1.3.0","ajax_url":"https:\/\/ld-wp73.template-help.com\/wordpress\/prod_6014\/v1\/wp-admin\/admin-ajax.php"};</script>
<script type='text/javascript'>var JetTabsSettings = {"ajaxurl":"https:\/\/ld-wp73.template-help.com\/wordpress\/prod_6014\/v1\/wp-admin\/admin-ajax.php","isMobile":"false","templateApiUrl":"https:\/\/ld-wp73.template-help.com\/wordpress\/prod_6014\/v1\/wp-json\/jet-tabs-api\/v1\/elementor-template","devMode":"false"};</script>
<script type='text/javascript'>var JetTricksSettings = {"elements_data":{"sections":{"b247187":{"view_more":false,"particles":"false","particles_json":""},"d574338":{"view_more":false,"particles":"false","particles_json":""},"0b3aa23":{"view_more":false,"particles":"false","particles_json":""},"20f3c01":{"view_more":false,"particles":"false","particles_json":""},"3010fef":{"view_more":false,"particles":"false","particles_json":""},"fab10c5":{"view_more":false,"particles":"false","particles_json":""},"188ed6b":{"view_more":false,"particles":"false","particles_json":""},"8f24911":{"view_more":false,"particles":"false","particles_json":""},"dc0d8ba":{"view_more":false,"particles":"false","particles_json":""},"4e8a6b7":{"view_more":false,"particles":"false","particles_json":""},"5fc7308":{"view_more":false,"particles":"false","particles_json":""},"e586246":{"view_more":false,"particles":"false","particles_json":""},"81611c7":{"view_more":false,"particles":"false","particles_json":""},"8b04860":{"view_more":false,"particles":"false","particles_json":""},"e54b38f":{"view_more":false,"particles":"false","particles_json":""},"cb7d1f8":{"view_more":false,"particles":"false","particles_json":""},"e09df03":{"view_more":false,"particles":"false","particles_json":""},"2a9218a":{"view_more":false,"particles":"false","particles_json":""}},"columns":[],"widgets":{"f1baf9d":[],"2a4dc43":[],"712e37d":[],"a69409e":[],"1aecb79":[],"66ce06e":[],"6a6f8a3":[],"25f4122":[],"214b3c7":[],"e64959b":[],"ee0dfe2":[],"01c3e01":[],"6601391":[],"284e609":[],"ecc3bd7":[],"5df6c5a":[],"8a07387":[],"fbd8ba5":[],"2b37bce":[],"0ac7804":[],"44586fd":[],"efccc34":[],"62524d9":[],"37d2bf7":[],"23db46e":[],"eef757f":[],"a2690ad":[],"58d9902":[],"2b066da":[],"afa48df":[],"5129035":[],"3b75e9b":[],"aac1f67":[],"d420d52":[],"93c4ebc":[],"b7abac1":[],"2167d39":[],"e07d5c9":[],"b7a664f":[],"172f5b6":[],"8978457":[],"ed28674":[],"fef9c8b":[],"c02e99a":[],"951a537":[],"02d4329":[],"bccfd5b":[],"012b201":[],"513759f":[],"8bf915b":[],"e9a5286":[],"43b26ec":[],"227c1e2":[],"5c3e8fb":[],"f6c402e":[],"65174fd":[],"3778261":[],"05bc3f7":[],"a54ec3a":[],"271b5e5":[],"24a6677":[],"cbc0dfa":[],"1389382":[],"38d6ed7":[],"41b7a51":[],"4ab0fdd":[],"cd7aadc":[],"e8de359":[],"5dba95a":[],"52f21b0":[],"8cd473d":[]}}};</script>
<script type='text/javascript'>var JetBlogSettings = {"ajaxurl":"https:\/\/ld-wp73.template-help.com\/wordpress\/prod_6014\/v1\/wp-admin\/admin-ajax.php"};</script>
<script defer src="{{asset('wp-content/cache/autoptimize/js/autoptimize_dd05d582c0a7bf0cb47c352a6d5a00b6.js')}}"></script>
</body>
</html>
